### ISSUE TITLE
Data is not saved in 5.26 RC

### ISSUE THREAD

**Issue by Four-Ninez** [JulianR0/CLevels#6]
I guess the next AngelScript update ruined this feature, so I think it would be better to fix it

**Comment by JulianR0** [comment]
I'm aware of this.

The issue with 5.26 is that they changed how plugins are loaded. Previously, plugins would stick between map changes, which SCXPM relied on to save data. Now, plugins that register any custom entity automatically reload themselves after each map change.

This is where the issue happens: When the server starts, `PluginInit()` loads the data from disk, and it is stored on memory. Then, on each map change, the `MapInit()` call saves the data back to the disk.

For this to work correctly, the data needs to be loaded first, and a "flag" is set upon load.

Because 5.26 causes the SCXPM plugin to reload itself on each map change, this flag is reset, and the data always re-initializes, never giving it a chance to write back to disk.

The `MapChange` hook would not work, either. Because the plugin auto-reloads itself first THEN the hook gets called next, in that order. Any data stored in memory was already lost, so nothing can be saved to disk at that point.

Hence the only solution I've found for 5.26 is to constantly write the data to disk every second or so.
It's very ugly but I haven't found other method so far.

**Comment by Four-Ninez** [comment]
Urgh, another update - another ruined feature

**Comment by Four-Ninez** [comment]
Hmm, I guess the Sven devs have solved the problems, so I'm closing this repository (yeh, saves starts working again)
